# Generated by Django 2.2.1 on 2019-09-05 21:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_nonce', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('txnid', models.CharField(blank=True, max_length=25, null=True)),
                ('result', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_name_en', models.CharField(max_length=200, null=True)),
                ('course_name_ar', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(default='This is a default descriptin', max_length=4000)),
                ('description_en', models.TextField(default='This is a default descriptin', max_length=4000, null=True)),
                ('description_ar', models.TextField(default='This is a default descriptin', max_length=4000, null=True)),
                ('price', models.FloatField(max_length=4)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateTimeField()),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(default='011', max_length=128, null=True, region=None)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tutors', to='trainboard.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('country', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1, null=True)),
                ('mobile', models.CharField(default='', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{8,13}')])),
                ('id_num', models.PositiveIntegerField(null=True, unique=True)),
                ('id_image', models.ImageField(null=True, upload_to='images/')),
                ('certificate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='trainboard.Certificate')),
                ('course', models.ManyToManyField(related_name='students', to='trainboard.Course')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='trainboard.Accountant')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='trainboard.Course'),
        ),
        migrations.CreateModel(
            name='Braintree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_token', models.TextField(max_length=500, verbose_name='client token')),
                ('payment_once', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=25, null=True)),
                ('payment_mode', models.BooleanField(default=False)),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='braintree', to='trainboard.Student')),
            ],
        ),
        migrations.AddField(
            model_name='accountant',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='accountants', to='trainboard.Student'),
        ),
    ]
