# Generated by Django 2.2.1 on 2019-09-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile',
            new_name='mobile_no',
        ),
    ]
