# Generated by Django 2.2.1 on 2019-09-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainboard', '0002_auto_20190906_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_no',
            new_name='mobile',
        ),
    ]
