# Generated by Django 2.2.1 on 2019-09-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainboard', '0003_auto_20190908_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
    ]
