# Generated by Django 2.2.1 on 2019-09-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainboard', '0005_student_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
    ]
