# Generated by Django 2.2.1 on 2019-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainboard', '0007_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description_ar',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
